name: 'kkb-agit'

inputs:
  agit_incoming_url:
    required: true

runs:
  using: 'composite'

  steps:
    - name: Send agit
      shell: bash
      run: |
        START_TS="$(date +%Y-%m-%d) 00:00:00"
        echo "START_TS : ${START_TS}"

        END_TS="$(date +%Y-%m-%d) 01:00:00"
        echo "END_TS : ${END_TS}"
        
        START_EPOCH=$(date --date "$START_TS" +%s)
        echo "START_EPOCH : ${START_EPOCH}"

        END_EPOCH=$(date --date "$END_TS" +%s)
        echo "END_EPOCH : ${END_EPOCH}"


        TODAY="$(date +%m%d)"
        TODAY_6=`date -d "+6 days" "+%m%d"`
        echo "TODAY : ${TODAY}"
        echo "TODAY_6 : ${TODAY_6}"
        
        EVENT=""
        while read LINE; do
          BTH="${LINE:0:4}"
          if [ $BTH -ge $TODAY ] && [ $TODAY_6 -ge $BTH ]; then
        		EVENT="${EVENT}${LINE}\n"
          fi
        done < ./.github/datas/bth.dat


        TEXT=${{ inputs.agit_loan_text }}
        # "@group 매주 월요일\n\n#여신플랫폼 *캠프* \n*대출서비스* \n -\n*신용대출* \n -\n*연계대출* \n -\n*대출플랫폼* \n -\n*오토론* \n -\n*여신관리* \n -\n*신용정보* \n -\n*공통및기타* \n -\n\n#담보여신 *캠프* \n -\n\n#개인사업자 *캠프* \n -"

        if [ -z ${EVENT} ]; then
          echo "빈칸"
        else
          TEXT="금주의 이벤트\n${EVENT}${TEXT}"
        fi

        curl -k -X POST --data-urlencode \
        "payload={ \
          \"text\": \"${TEXT}\", \
          \"schedule\": { \
            \"title\": \"여신플랫폼개발(코어)업무공유\", \
            \"is_allday\": true, \
            \"color\": \"blue\", \
            \"starts_at\": ${START_EPOCH}, \
            \"ends_at\": ${END_EPOCH} \
          } \
        }" \
        ${{ inputs.agit_incoming_url }}
