name : 'kkb-agit-loan-weekly'

on:
    workflow_dispatch:
    
    schedule:
        - cron: "13 6 * * 0,1,6"
    
jobs:
  kkb-agit-loan:
      name: 'Agit push'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Send KKB agit
          uses: ./.github/actions/kkb-agit

          with:
              agit_incoming_url: ${{secrets.AGIT_INCOMING_URL}}
              
      
  # echo:
  #   runs-on: ubuntu-latest 
  #   steps:
  #     - run: echo 'Hello actions'

  # pwd-ls:
  #   name : PWD&LS
  #   runs-on: ubuntu-latest
  #   steps:
  #       - name: print working directory
  #         run: pwd
  #       - name: List files
  #         run: ls -al
