name : 'kkb-agit-loan-weekly'

on: push
    
jobs:
  echo:
    runs-on: ubuntu-latest 
    steps:
      - run: echo 'Hello actions'

  pwd-ls:
    name : PWD&LS
    runs-on: ubuntu-latest
    steps:
        - name: print working directory
          run: pwd
        - name: List files
          run: ls -al
